### ISSUE TITLE
Requirements not found aiohttp==3.9.5  

### ISSUE THREAD

**Issue by Node815** [Amateur-God/home-assistant-technitiumdns#28]
# Problem/Motivation

Error occurred tonight (out of the blue) 

## Expected behavior

Should not happen! 

## Actual behavior

Fails to load in Home Assistant after restarting HASS And displays:

![image](https://github.com/user-attachments/assets/3453f5ff-874c-40d0-af21-f0c862f2e3d7)

## Steps to reproduce

Reinstalled and it didn't work:
![image](https://github.com/user-attachments/assets/2e5905b6-d3a0-4c89-880a-a9d9673856c4)

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 6:34:44 PM (3 occurrences)
Last logged: 6:34:50 PM

Unable to install package aiohttp==3.9.5: ERROR: Cannot install aiohttp==3.9.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**FROM Technitium**

 
![image](https://github.com/user-attachments/assets/b0b84534-5cfb-43fc-b796-9b4d0b58c925)

**Comment by Amateur-God** [comment]
fixed in release https://github.com/Amateur-God/home-assistant-technitiumdns/releases/tag/v2.2.1 

please try refreshing info in HACS and try download/install again

**Comment by firestrife23** [comment]
Updated to 2.2.2 and it's still throwing me an error about the requirement not found: aiohttp==3.9.5
